### ISSUE TITLE
UI 컴포넌트 보완해보기

### ISSUE THREAD

**Issue by chanwukim** [2hundred2ne2/in_my_link#17]
같이 만든 UI 컴포넌트를 사용해보면서 느낀 개선사항을 코멘트로 자유롭게 남겨주세용

**Comment by chanwukim** [comment]
- [ ] 변수/클래스 foreground-invert 가 필요함. (배경과 반전된 텍스트 색)

**Comment by chanwukim** [comment]
Button
  - [ ] large사이즈: figma에서 높이가 56px이라서, min-h-14를 추가하면 될 것 같아요

**Comment by chanwukim** [comment]
Card
- 컴포넌트 내부에서  `inline-flex` 와 `p-2`가 적용 되어있는데, 이 컴포넌트를 사용할 때 prop으로 넘겨주는건 어떤지
- `variant`가 `default`가 있는데, 기본값으로 `muted`로 되어있음!
```ts
export function Card({ variant = "muted", className, children, ...rest }: CardProps) {
  const classNames = `${variants[variant]} inline-flex p-2 ${className}`;
  return (
    <div className={classNames} {...rest}>
      {children}
    </div>
  );
}

```

**Comment by chanwukim** [comment]
Button에 focus 상태 스타일이 지정되어있는데, `input`이나 `tabs`같은 요소에도 스타일 통일할지에 대해 논의하기

**Comment by chanwukim** [comment]
- [ ] Tabs 각 버튼 눌릴때 스타일 변경

**Comment by 2hundred2ne2** [comment]
- button클릭 시 스타일변경

#28
